# CodeRabbit configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

language: en-US

reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false

chat:
  auto_reply: true
